{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "watchman.fullname" . }}
  labels:
    {{- include "watchman.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secret.nvidiaApiKey }}
  NVIDIA_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.esPassword }}
  ES_PASS: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.telegramBotToken }}
  TELEGRAM_BOT_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.lokiPassword }}
  LOKI_PASS: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.lokiToken }}
  LOKI_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.datadogApiKey }}
  DD_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.datadogAppKey }}
  DD_APP_KEY: {{ . | quote }}
  {{- end }}
{{- end }}
